from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("email",sa.String(320),nullable=False,unique=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("password_hash",sa.String(512),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_users_email","users",["email"])
    op.create_table("audiences",sa.Column("id",sa.String(36),primary_key=True),sa.Column("owner_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_audiences_owner_id","audiences",["owner_id"])
    op.create_table("contacts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("audience_id",sa.String(36),sa.ForeignKey("audiences.id",ondelete="CASCADE"),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("first_name",sa.String(80)),sa.Column("last_name",sa.String(80)),sa.Column("unsubscribed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("audience_id","email",name="uq_contact_audience_email"))
    op.create_index("ix_contacts_audience_id","contacts",["audience_id"]); op.create_index("ix_contacts_email","contacts",["email"])
    op.create_table("campaigns",sa.Column("id",sa.String(36),primary_key=True),sa.Column("owner_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("audience_id",sa.String(36),sa.ForeignKey("audiences.id",ondelete="RESTRICT"),nullable=False),sa.Column("name",sa.String(140),nullable=False),sa.Column("subject",sa.String(200),nullable=False),sa.Column("body_html",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("scheduled_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_campaigns_owner_id","campaigns",["owner_id"]); op.create_index("ix_campaigns_audience_id","campaigns",["audience_id"]); op.create_index("ix_campaigns_status","campaigns",["status"])
    op.create_table("campaign_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("campaign_id",sa.String(36),sa.ForeignKey("campaigns.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="queued"),sa.Column("total_recipients",sa.Integer(),nullable=False,server_default="0"),sa.Column("sent_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("failed_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)))
    op.create_index("ix_campaign_runs_campaign_id","campaign_runs",["campaign_id"]); op.create_index("ix_campaign_runs_status","campaign_runs",["status"])
    op.create_table("deliveries",sa.Column("id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),sa.ForeignKey("campaign_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("contact_id",sa.String(36),sa.ForeignKey("contacts.id",ondelete="RESTRICT"),nullable=False),sa.Column("tracking_token",sa.String(64),nullable=False,unique=True),sa.Column("status",sa.String(24),nullable=False,server_default="queued"),sa.Column("provider_message_id",sa.String(255)),sa.Column("error_message",sa.String(500)),sa.Column("sent_at",sa.DateTime(timezone=True)))
    op.create_index("ix_deliveries_run_id","deliveries",["run_id"]); op.create_index("ix_deliveries_contact_id","deliveries",["contact_id"]); op.create_index("ix_deliveries_tracking_token","deliveries",["tracking_token"]); op.create_index("ix_deliveries_status","deliveries",["status"])
    op.create_table("campaign_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("delivery_id",sa.String(36),sa.ForeignKey("deliveries.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(24),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_campaign_events_delivery_id","campaign_events",["delivery_id"]); op.create_index("ix_campaign_events_event_type","campaign_events",["event_type"]); op.create_index("ix_events_delivery_type","campaign_events",["delivery_id","event_type"])
def downgrade():
    op.drop_index("ix_events_delivery_type",table_name="campaign_events"); op.drop_index("ix_campaign_events_event_type",table_name="campaign_events"); op.drop_index("ix_campaign_events_delivery_id",table_name="campaign_events"); op.drop_table("campaign_events")
    op.drop_index("ix_deliveries_status",table_name="deliveries"); op.drop_index("ix_deliveries_tracking_token",table_name="deliveries"); op.drop_index("ix_deliveries_contact_id",table_name="deliveries"); op.drop_index("ix_deliveries_run_id",table_name="deliveries"); op.drop_table("deliveries")
    op.drop_index("ix_campaign_runs_status",table_name="campaign_runs"); op.drop_index("ix_campaign_runs_campaign_id",table_name="campaign_runs"); op.drop_table("campaign_runs")
    op.drop_index("ix_campaigns_status",table_name="campaigns"); op.drop_index("ix_campaigns_audience_id",table_name="campaigns"); op.drop_index("ix_campaigns_owner_id",table_name="campaigns"); op.drop_table("campaigns")
    op.drop_index("ix_contacts_email",table_name="contacts"); op.drop_index("ix_contacts_audience_id",table_name="contacts"); op.drop_table("contacts")
    op.drop_index("ix_audiences_owner_id",table_name="audiences"); op.drop_table("audiences"); op.drop_index("ix_users_email",table_name="users"); op.drop_table("users")
